<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net6.0</TargetFramework>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\\Domain\\HandMidiControllerDDD.Domain.csproj" />
		<ProjectReference Include="..\\Application\\HandMidiControllerDDD.Application.csproj" />
		<ProjectReference Include="..\\Infrastructure\\HandMidiControllerDDD.Infrastructure.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="10.0.1" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="7.0.0" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="7.0.0" />
		<PackageReference Include="prometheus-net.AspNetCore" Version="8.2.1" />
	</ItemGroup>
	<ItemGroup>
  <!-- Treat application.json as “Content” and always copy it to the output -->
  <None Update="application.json">
    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
  </None>
</ItemGroup>
</Project>